spring.application.name=expenseTraker

spring.dataresource.url = jdbc:postgressql://localhost:5432/expense_traker_db
spring.dataresource.username = root
sprin.dataresource.password = MY_DB_EXPENSE

spring.jpa.hibernate.ddl-auto = update